### ISSUE TITLE
`cargo mobile init` is not working, return env problem

### ISSUE THREAD

**Issue by bajrangCoder** [wusyong/cargo-mobile#179] opened 2023-07-02 00:56 UTC
**Bug**
`cargo mobile init` isn't working, I am currently on **Garuda linux**(a arch based linux distro).
I have installed required thing given on tauri mobile website and also installed Android Studio and all mentioned sdk and ndk,
And also set environment variable as you can check 👇

![Screenshot_20230702_061426](https://github.com/tauri-apps/tauri-mobile/assets/71929976/27f7869f-e457-45de-8b16-cf29a82059aa)

and here what i get when i run `cargo mobile init` 👇 (this is my second try, it didn't ask for project name etc in second time)

![Screenshot_20230702_062336](https://github.com/tauri-apps/tauri-mobile/assets/71929976/e8f317a1-08d6-4e32-a3de-1be57a26c171)

**Comment by amrbashir** [comment] 2023-07-03 14:28
could you do `echo $ANDROID_HOME` in the shell before running `cargo mobile init`?

**Comment by amrbashir** [comment] 2023-07-03 14:29
Also this repo is a low-level library that is used by tauri, if you want to use tauri, check this https://tauri.app/blog/2023/03/01/create-tauri-app-version-3-released#tauri-20-alpha--mobile-support to bootstrap a tauri project for mobile.

**Comment by bajrangCoder** [comment] 2023-07-04 00:48
> could you do `echo $ANDROID_HOME` in the shell before running `cargo mobile init`?

it prints the path of sdk but still the same error

**Comment by bajrangCoder** [comment] 2023-07-04 00:49
> Also this repo is a low-level library that is used by tauri, if you want to use tauri, check this https://tauri.app/blog/2023/03/01/create-tauri-app-version-3-released#tauri-20-alpha--mobile-support to bootstrap a tauri project for mobile.

after running tauri android init  
it also gives same error

**Comment by amrbashir** [comment] 2023-07-04 01:34
That's weird, how about using bash instead of fish?

**Comment by bajrangCoder** [comment] 2023-07-04 10:32
Hmm
Ok I will try.

**Comment by bajrangCoder** [comment] 2023-07-05 16:10
Yes it worked wit bash

**Comment by amrbashir** [comment] 2023-07-05 17:28
alright, I will close it then, looks like the problem is with your fish shell setup, I am not a fish user so I can't help.

**Closed as not planned by amrbashir** 2023-07-05 17:28 UTC

**Comment by gustavojoaquin** [comment] 2023-09-16 01:53
It can be fixed adding `export NDK_HOME=/opt/android-ndk` in your `~/.zshrc` or `~/.bashrc`

**Comment by bajrangCoder** [comment] 2023-09-16 06:30
> It can be fixed adding `export NDK_HOME=/opt/android-ndk` in your `~/.zshrc` or `~/.bashrc`

It's already fixed, by setuping the variable in fish config file

**Comment by bryan-lott** [comment] 2024-01-25 04:05
In case anyone else runs into this... the issue is caused by the fish shell. What you need in your `~/.config/fish/config.fish` file is the following:

specifically the `-gx` sets the variable to be global and export to subshells

```
# Android SDK
set -gx ANDROID_HOME $HOME/android
set -gx ANDROID_SDK_ROOT $ANDROID_HOME
fish_add_path $ANDROID_HOME/cmdline-tools/latest/bin $ANDROID_HOME/platform-tools $ANDROID_HOME/tools $ANDROID_HOME/tools/bin
```
