### ISSUE TITLE
cargo tauri android init failed in windwo os for yew and leptos template

### ISSUE THREAD

**Issue by dhrubrawat66** [wusyong/cargo-mobile#275] opened 2024-02-21 13:26 UTC
1.  i have window os 11
2. i'm using following tauri cli

![Screenshot 2024-02-21 190141](https://github.com/tauri-apps/cargo-mobile2/assets/85351405/c853733f-233e-417d-b311-aff340f9d2f3)
3.  i created the the tauri app by using -->  cargo create-tauri-app --beta
![Screenshot 2024-02-21 190141](https://github.com/tauri-apps/cargo-mobile2/assets/85351405/1fa3d54c-a9de-4af4-9642-9d1f0a440aa7)
4. but when i try to run ->"cargo tauri android init" command it runs following error
![Screenshot 2024-02-21 190141](https://github.com/tauri-apps/cargo-mobile2/assets/85351405/d5d90a4c-5378-4fa6-b344-7d66eb97cc2d)
6. please try to solve this problem

**Comment by dhrubrawat66** [comment] 2024-02-26 09:06
cargo tauri android init  command works if the project and cargo HOME is in same folder. But is not works if the project and cargo HOME folder are in distinct folder.

**Comment by amrbashir** [comment] 2024-02-26 15:41
Closing as duplicate of https://github.com/tauri-apps/tauri/issues/8531, could you please provide the problematic directory structure in that repo as I couldn't reproduce the issue before and your directory structure might help? Also if there is any `.gitignore` files, please include them

**Closed as completed by amrbashir** 2024-02-26 15:41 UTC
